# Generated by Django 6.1 on 2026-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='craft',
            field=models.CharField(blank=True, choices=[('embroidery', 'Embroidery'), ('wood-leather', 'Wood & Leather'), ('metal-jewelry', 'Metal Jewelry')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customizable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='occasions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
